# -*- coding: utf-8 -*-
"""ASNZS_1170_0_2002.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vXdyWK3uu6MncNY87YmABolL_-iVVzg2

#AS/NZS 1170.0:2002 .py method

This method references the following standard:
AS/NZS 1170.0:2002 (incorporating Amendment Nos 1,2,3,4 and 5)

Method developed 28 August 2021
(c) BVT Consulting Ltd

Developed - MMB

Reviewed -

###Initialise  Dependents and Libraries
"""

import pandas as pd

"""#Annual Probability of Exceedance

Given the Design working life and the Importance level, this function returns the Annual probability of exceedance for Wind, Snow and Earthquake, as given in Table 3.3.
"""

#@title Table 3.3
#recreate table 3.3
table3_3 = pd.DataFrame(
{"Wind ULS":['1/100',
             '1/25','1/100','1/250','1/1000',
             '1/25','1/250','1/500','1/1000',
             '1/50','1/250','1/500','1/1000',
             '1/100','1/500','1/1000','1/2500',
             '1/250','1/1000','1/2500','*'],
 "Snow ULS":['1/50',
             '1/25','1/50','1/100','1/250',
             '1/25','1/50','1/100','1/250',
             '1/25','1/50','1/100','1/250',
             '1/50','1/150','1/250','1/500',
             '1/150','1/250','1/500','*'],
 "Earthquake ULS":['1/100',
             '1/25','1/100','1/250','1/1000',
             '1/25','1/250','1/500','1/1000',
             '1/50','1/250','1/500','1/1000',
             '1/100','1/500','1/1000','1/2500',
             '1/250','1/1000','1/2500','*'],
 "SLS1":    ['1/25',
             '-','1/25','1/25','1/25',
             '-','1/25','1/25','1/25',
             '-','1/25','1/25','1/25',
             '-','1/25','1/25','1/25',
             '-','1/25','1/25','1/25'],
 "SLS2":    [' ',
             ' ',' ',' ',' ',
             '-','-','-','1/250',
             '-','-','-','1/250',
             '-','-','-','1/500',
             '-','-','-','*'],
 },
 index = pd.MultiIndex.from_tuples([('Construction equipment',2),
                                    ('Less than 6 months',1),
                                    ('Less than 6 months',2),
                                    ('Less than 6 months',3),
                                    ('Less than 6 months',4),
                                    ('5 years',1),
                                    ('5 years',2),
                                    ('5 years',3),
                                    ('5 years',4),
                                    ('25 years',1),
                                    ('25 years',2),
                                    ('25 years',3),
                                    ('25 years',4),
                                    ('50 years',1),
                                    ('50 years',2),
                                    ('50 years',3),
                                    ('50 years',4),
                                    ('100 years or more',1),
                                    ('100 years or more',2),
                                    ('100 years or more',3),
                                    ('100 years or more',4),
                                    ],
                                   names=['Design working life','Importance level'])    
)

table3_3

def annual_probability_of_exceedence(Design_Working_Life,Importance_Level,Limit_State):

    df1 = table3_3.loc[(Design_Working_Life, Importance_Level),Limit_State]

    return df1

annual_probability_of_exceedence('50 years',4,'Wind ULS')