# -*- coding: utf-8 -*-
"""NZS_1170_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dqsUpCzIq-cRgnJhh3CtCpTRoeByDu1s
"""

Z = .30
